# This is a basic workflow to help you get started with Actions

name: Mi primera Integracion continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      nombre: "Jean"
      apellidos: "Celiz Paredes"
      edad: 34

      user: ${{ secrets.USER }}
      password: ${{ secrets.PASSWORD }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Mi Presentacion
      - name: Presentacion
        run: |
          echo "Impresion de mi presentacion:"
          echo "mi nombre es: ${{ env.nombre }}"
          echo "mi apellido es: ${{ env.apellidos }}"
          echo "mi edad es: ${{  env.edad }}"

      # Mis datos generales
      - name: datos generales
        run: 
          echo "Impresion de Mis Datos Generales"
          echo "Carrera Ingenieria de Sistemas"

      # IMPRESION DE VARIABLES SECRETAS
      - name: variable de entorno secreto
        run: 
          echo "Mi usuario es : ${{ env.user }}"
          echo "Mi contraseña es : ${{ env.password }}"

      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
